// Card bank. One prompt per line. Each is read as "Name 3 ...".
// Use <em>...</em> to highlight a word. Run  node scripts/check-questions.mjs  before opening a PR.
window.QUESTIONS = [
  "countries in South America that <em>aren't</em> Brazil",
  "US presidents who <em>aren't</em> on money",
  "women who've won the Oscar for Best Actress",
  "animals that start with <em>Q</em>",
  "cereals <em>without</em> an O in the name",
  "Asian countries that aren't China, Japan, or Korea",
  "NBA players who <em>never</em> won a title",
  "songs from before you were born",
  "fast food chains that <em>don't</em> sell burgers",
  "state capitals that aren't their state's biggest city",
  "female scientists",
  "things in your fridge right now, no looking",
  "African countries other than Egypt",
  "famous Black inventors",
  "Disney villains",
  "European capitals that aren't London, Paris, or Rome",
  "things you'd find in a hospital",
  "Beatles songs",
  "pizza toppings that aren't meat",
  "pizza chains",
  "Pixar movies",
  "cheeses that aren't cheddar",
  "green vegetables",
  "Olympic sports that aren't track or swimming",
  "words that rhyme with <em>cat</em>",
  "Taylor Swift songs",
  "things you pack for a beach trip",
  "board games",
  "famous people named Michael",
  "dog breeds bigger than a lab",
  "Filipino dishes",
  "car brands that aren't American",
  "musical instruments with strings",
  "Harry Potter characters who aren't Harry, Ron, or Hermione",
  "things that are yellow",
  "cartoons from the 90s",
  "NFL teams with animal names",
  "planets that aren't Earth",
  "breakfast foods that aren't eggs",
  "reality TV shows",
  "things you do on a first date",
  "types of pasta",
  "famous landmarks outside the US",
  "apps on your phone right now",
  "desserts with chocolate",
  "things that have wheels",
  "NFL quarterbacks, past or present",
  "fruits that grow on trees",
  "superheroes who <em>can't</em> fly",
  "things in a junk drawer",
  "countries that start with <em>M</em>",
  "Christmas songs",
  "jobs that need a uniform",
  "things you'd yell at a referee",
  "celebrity couples",
  "Marvel movies",
  "Mexican dishes that aren't tacos",
  "things that are cold",
  "Friends characters",
  "body parts with only 3 letters",
  "Michael Jackson songs",
  "ocean animals that aren't fish",
  "kinds of shoes",
  "things you find in a bathroom",
  "Star Wars characters",
  "colors that aren't in the rainbow",
  "kitchen appliances",
  "words that start with <em>Z</em>",
  "spices",
  "birds that can't fly",
  "Justin Bieber songs",
  "US states that start with <em>N</em>",
  "famous chefs",
  "things people are afraid of",
  "sodas that aren't Coke or Pepsi",
  "90s boy bands or girl groups",
  "languages other than English and Spanish",
  "things that come in pairs",
  "video game characters",
  "candy bars",
  "things you'd see at a wedding",
  "famous duos",
  "Netflix shows",
  "things that are sticky",
  "animals with stripes",
  "sports that use a net",
  "fictional detectives",
  "things you plug in",
  "ice cream flavors that aren't vanilla or chocolate",
  "cities in Texas",
  "rappers",
  "things you'd find in a classroom",
  "Broadway musicals",
  "things that smell good",
  "words that rhyme with <em>day</em>",
  "citrus fruits",
  "famous painters",
  "things that are round",
  "cities that have hosted the Olympics",
  "animals that live in Australia",
  "things that fly that <em>aren't</em> birds",
  "condiments",
  "nicknames for grandma",
  "things in a first aid kit",
  "actors who played James Bond",
  "Shrek characters",
  "things you'd bring camping",
  "types of bread",
  "athletes who <em>aren't</em> American",
  "horror movies",
  "things people do on a Sunday",
  "Pokémon",
  "things you'd find on a farm",
  "Beyoncé songs",
  "SpongeBob characters",
  "sandwiches",
  "things with buttons",
  "things that make noise at night",
  "Greek gods",
  "rivers",
  "hairstyles",
  "things that are soft",
  "US national parks",
  "soups",
  "Mario Kart characters",
  "words that mean <em>happy</em>",
  "YouTubers",
  "insects",
  "things you'd find at a carnival",
  "famous Canadians",
  "card games",
  "things that melt",
  "Simpsons characters",
  "Caribbean islands you could vacation on",
  "cocktails",
  "Best Picture Oscar winners",
  "things you'd say after stubbing your toe (keep it clean)",
  "dances",
  "fictional kings or queens",
  "things that are orange"
];
