// Name 3 in 5 card bank.
// Each prompt is read as "Name 3 ...", so write only the part after that.
// Use <em>...</em> to highlight a twist. Categories marked adult: true only appear in 18+ mode.
// Run  node scripts/check-questions.mjs  before opening a pull request.
window.CATEGORIES = [
  {
    id: "screen",
    name: "Screen & Sound",
    q: [
      "Pixar movies",
      "Disney villains",
      "Marvel movies",
      "Beatles songs",
      "Taylor Swift songs",
      "Michael Jackson songs",
      "Beyoncé songs",
      "Justin Bieber songs",
      "Drake songs",
      "Adele songs",
      "Christmas songs",
      "songs from before you were born",
      "women who've won the Oscar for Best Actress",
      "Best Picture Oscar winners",
      "horror movies",
      "reality TV shows",
      "Netflix original shows",
      "cartoons from the 90s",
      "Friends characters",
      "Simpsons characters",
      "SpongeBob characters",
      "Shrek characters",
      "Star Wars characters",
      "Harry Potter characters who aren't Harry, Ron, or Hermione",
      "superheroes who <em>can't</em> fly",
      "actors who played James Bond",
      "Broadway musicals",
      "90s boy bands or girl groups",
      "rappers",
      "YouTubers",
      "celebrity couples",
      "fictional detectives",
      "movies with a number in the title",
      "movies set in space",
      "TV doctors",
      "TV shows set in a high school",
      "songs with a color in the title",
      "bands with <em>The</em> in their name",
      "one-hit wonders",
      "Tom Hanks movies",
      "Will Smith movies",
      "Leonardo DiCaprio movies",
      "Disney princesses",
      "animated movies that <em>aren't</em> Disney or Pixar",
      "sitcoms",
      "talk show hosts",
      "game shows",
      "movie villains who <em>aren't</em> from Disney",
      "Batman villains",
      "Avengers",
      "Muppets",
      "Looney Tunes characters",
      "famous movie dogs",
      "movies based on books",
      "TV families",
      "singers known by one name",
      "country singers",
      "K-pop groups or artists",
      "Super Bowl halftime performers",
      "songs about cars or driving",
      "Christmas movies",
      "Game of Thrones characters",
      "The Office characters",
      "Nickelodeon shows",
      "Lord of the Rings characters",
      "movie sequels",
      "famous movie lines"
    ]
  },
  {
    id: "world",
    name: "Around the World",
    q: [
      "countries in South America that <em>aren't</em> Brazil",
      "Asian countries that aren't China, Japan, or Korea",
      "African countries other than Egypt",
      "European capitals that aren't London, Paris, or Rome",
      "state capitals that aren't their state's biggest city",
      "countries that start with <em>M</em>",
      "US states that start with <em>N</em>",
      "cities in Texas",
      "famous landmarks outside the US",
      "Caribbean islands you could vacation on",
      "rivers",
      "US national parks",
      "cities that have hosted the Olympics",
      "languages other than English and Spanish",
      "landlocked countries",
      "countries in the Middle East",
      "cities in California",
      "cities in Florida",
      "countries that still have a king or queen",
      "deserts",
      "mountain ranges",
      "oceans and seas",
      "countries where people drive on the left",
      "cities in Italy",
      "cities in Canada",
      "US states with two words in their name",
      "countries ending in <em>-stan</em>",
      "countries that start with <em>S</em>",
      "capital cities in Asia",
      "famous bridges",
      "famous skyscrapers or towers",
      "honeymoon destinations",
      "countries that border China",
      "countries that border Germany",
      "US states that border Canada",
      "US states along the Mississippi River",
      "cities with an NBA team",
      "cities with a subway system",
      "countries famous for their beaches",
      "wonders of the world, old or new",
      "Spanish-speaking countries that <em>aren't</em> Mexico or Spain",
      "French-speaking countries that <em>aren't</em> France",
      "countries in Northern Europe",
      "volcanoes",
      "US states that start with a vowel",
      "famous streets",
      "airports, by name or code",
      "lakes",
      "cities you've visited",
      "countries with a cross on their flag",
      "cities in Mexico",
      "cities in Japan",
      "Australian cities",
      "famous castles or palaces",
      "currencies",
      "tiny countries",
      "theme parks",
      "cities that start with <em>San</em> or <em>Santa</em>",
      "islands that are their own country",
      "countries with a red, white, and blue flag that <em>aren't</em> the US"
    ]
  },
  {
    id: "food",
    name: "Food & Drink",
    q: [
      "cereals <em>without</em> an O in the name",
      "fast food chains that <em>don't</em> sell burgers",
      "pizza toppings that aren't meat",
      "pizza chains",
      "cheeses that aren't cheddar",
      "green vegetables",
      "Filipino dishes",
      "breakfast foods that aren't eggs",
      "types of pasta",
      "desserts with chocolate",
      "fruits that grow on trees",
      "Mexican dishes that aren't tacos",
      "spices",
      "sodas that aren't Coke or Pepsi",
      "candy bars",
      "sandwiches",
      "soups",
      "condiments",
      "types of bread",
      "citrus fruits",
      "ice cream flavors that <em>aren't</em> vanilla or chocolate",
      "Girl Scout cookies",
      "types of nuts",
      "foods that are white",
      "foods you eat with a spoon",
      "foods that come in a can",
      "hot dog toppings",
      "coffee drinks",
      "types of tea",
      "Thanksgiving dishes",
      "foods on a stick",
      "Italian dishes that aren't pizza or pasta",
      "Chinese takeout dishes",
      "Japanese foods that <em>aren't</em> sushi",
      "Indian dishes",
      "spicy foods",
      "red fruits",
      "foods that start with <em>P</em>",
      "potato chip brands or flavors",
      "kinds of beans",
      "foods people put ketchup on",
      "things you'd throw on a grill",
      "salad dressings",
      "Starbucks drinks",
      "gum or mint brands",
      "fruits with a pit",
      "crunchy foods",
      "pies",
      "cakes",
      "cookies",
      "sushi rolls",
      "things at a buffet",
      "pasta sauces",
      "foods named after places",
      "ice cream toppings",
      "sports or energy drinks",
      "orange foods",
      "things you dip in chocolate",
      "cuts of steak",
      "fish people eat",
      "cereals with a mascot",
      "foods that are better cold"
    ]
  },
  {
    id: "game",
    name: "Game Day",
    q: [
      "NBA players who <em>never</em> won a title",
      "Olympic sports that aren't track or swimming",
      "NFL teams with animal names",
      "NFL quarterbacks, past or present",
      "athletes who <em>aren't</em> American",
      "sports that use a net",
      "board games",
      "card games",
      "Mario Kart characters",
      "Pokémon",
      "video game characters",
      "MLB teams",
      "NHL teams",
      "NBA teams whose names <em>don't</em> end in S",
      "famous boxers",
      "tennis players",
      "golfers",
      "soccer players",
      "women athletes",
      "sports played on ice",
      "sports without a ball",
      "fouls or penalties from any sport",
      "college football teams",
      "sports that use a stick or bat",
      "positions from any sport",
      "famous coaches",
      "things you'd see at a baseball game",
      "things in a gym",
      "yoga poses",
      "martial arts",
      "Winter Olympic sports",
      "video game consoles",
      "Nintendo games",
      "NASCAR or F1 drivers",
      "playground games",
      "pool or beach games",
      "things you'd yell at a referee",
      "sports movies",
      "athlete nicknames",
      "basketball terms",
      "football terms",
      "golf terms",
      "chess terms",
      "dice games",
      "party games",
      "mobile games",
      "Super Bowl winning teams",
      "countries that have won the World Cup",
      "things you need to play golf",
      "gym exercises",
      "WWE wrestlers",
      "skateboard or snowboard tricks",
      "things a coach yells",
      "Olympic gold medalists",
      "online multiplayer games",
      "things you'd find at a bowling alley",
      "things in a sporting goods store",
      "sports with a halftime",
      "famous stadiums or arenas",
      "mascots of any team"
    ]
  },
  {
    id: "wild",
    name: "Wild Things",
    q: [
      "animals that start with <em>Q</em>",
      "animals with stripes",
      "animals that live in Australia",
      "ocean animals that aren't fish",
      "birds that can't fly",
      "insects",
      "dog breeds bigger than a lab",
      "planets that aren't Earth",
      "animals with horns or antlers",
      "animals that hibernate",
      "animals that lay eggs that <em>aren't</em> birds",
      "reptiles",
      "animals that live in Africa",
      "farm animals",
      "cat breeds",
      "animals with spots",
      "nocturnal animals",
      "black and white animals",
      "baby animal names",
      "animals with more than four legs",
      "trees",
      "flowers",
      "types of clouds",
      "weather events",
      "elements on the periodic table",
      "bones in the body",
      "organs in the body",
      "things in space",
      "dinosaurs",
      "animals that live in trees",
      "animals that eat bugs",
      "animals that change color",
      "endangered animals",
      "bugs that bite or sting",
      "things that grow in a garden",
      "gemstones",
      "metals",
      "female scientists",
      "inventions from the last 50 years",
      "things in a science lab",
      "zoo animals",
      "pets that aren't cats or dogs",
      "herbs",
      "venomous animals",
      "animals that start with <em>B</em>",
      "mammals that live in the ocean",
      "rocks or minerals",
      "natural disasters",
      "parts of a plant",
      "Arctic or Antarctic animals",
      "animals with shells",
      "units of measurement",
      "types of shark",
      "types of whale",
      "animals with wings that aren't birds",
      "famous animals, real or fictional",
      "fish you could catch in a lake",
      "things a doctor checks at a physical",
      "animals that are faster than a human",
      "animals smaller than a mouse"
    ]
  },
  {
    id: "house",
    name: "Around the House",
    q: [
      "things in your fridge right now, no looking",
      "things in a junk drawer",
      "things in a bathroom",
      "kitchen appliances",
      "apps on your phone right now",
      "things you plug in",
      "things with buttons",
      "things that make noise at night",
      "things you'd find in a classroom",
      "things in a first aid kit",
      "things you'd bring camping",
      "things you pack for a beach trip",
      "kinds of shoes",
      "hairstyles",
      "things in a purse or wallet",
      "things in a car's glovebox",
      "furniture",
      "cleaning products",
      "things in a toolbox",
      "rooms in a house",
      "things in a garage",
      "things on a desk",
      "things in a medicine cabinet",
      "things on a bed",
      "chores",
      "things in a backpack",
      "things in an attic",
      "things you'd find under a couch cushion",
      "things that need batteries",
      "things with a screen",
      "kitchen utensils",
      "types of hats",
      "types of jackets or coats",
      "jewelry",
      "makeup products",
      "things at a hardware store",
      "things in a hotel room",
      "things at a grocery store checkout",
      "things you lose all the time",
      "things in a kid's bedroom",
      "things you charge every night",
      "streaming services",
      "social media apps",
      "things in a laundry room",
      "things you do before bed",
      "things you do every morning",
      "things in a waiting room",
      "keys on a keyboard",
      "things people collect",
      "things at a craft store",
      "things at a gas station",
      "things at Target",
      "things at a yard sale",
      "things you use to cut something",
      "types of pants",
      "fabrics",
      "things on a front porch",
      "things in a mailbox",
      "things that live in the back of a closet",
      "things you'd find in a dorm room"
    ]
  },
  {
    id: "words",
    name: "Wordplay",
    q: [
      "words that rhyme with <em>cat</em>",
      "words that rhyme with <em>day</em>",
      "words that start with <em>Z</em>",
      "words that mean <em>happy</em>",
      "body parts with only three letters",
      "words that rhyme with <em>light</em>",
      "words that rhyme with <em>bee</em>",
      "words that rhyme with <em>cake</em>",
      "words that end in <em>-ology</em>",
      "words that start with <em>QU</em>",
      "words with a double O",
      "words that mean <em>big</em>",
      "words that mean <em>small</em>",
      "words that mean <em>angry</em>",
      "words that mean <em>fast</em>",
      "words that mean <em>smart</em>",
      "words that start and end with the same letter",
      "palindromes",
      "words that start with <em>X</em>",
      "words that rhyme with <em>bear</em>",
      "words that rhyme with <em>moon</em>",
      "words that rhyme with <em>dog</em>",
      "words that rhyme with <em>money</em>",
      "compound words with <em>fire</em>",
      "compound words with <em>sun</em>",
      "compound words with <em>ball</em>",
      "words that end in <em>-ish</em>",
      "words that go before <em>-man</em>",
      "words that go after <em>hot</em>",
      "words that go after <em>book</em>",
      "words that go before <em>cake</em>",
      "words that go before <em>house</em>",
      "words with a silent <em>K</em>",
      "words with a silent <em>B</em>",
      "words that sound like a letter",
      "first names that are also words",
      "three-letter animals",
      "four-letter words you can say in church",
      "words that mean <em>tired</em>",
      "words that mean <em>weird</em>",
      "slang from the 90s",
      "Gen Z slang",
      "acronyms",
      "words borrowed from another language",
      "words that start with <em>J</em> that aren't names",
      "words that end in <em>-oo</em>",
      "things that start with <em>Th</em>",
      "two-letter words",
      "homophone pairs",
      "words that rhyme with <em>ring</em>",
      "words that rhyme with <em>love</em>",
      "words that rhyme with <em>cool</em>",
      "things that start with <em>K</em>",
      "things that start with <em>V</em>",
      "things that start with <em>Y</em>",
      "car brands that start with <em>M</em>",
      "words that end in <em>-tion</em>",
      "words with an apostrophe",
      "words that rhyme with <em>go</em>",
      "words that mean <em>no</em>"
    ]
  },
  {
    id: "people",
    name: "People & Past",
    q: [
      "US presidents who <em>aren't</em> on money",
      "famous Black inventors",
      "famous painters",
      "famous Canadians",
      "famous chefs",
      "famous people named Michael",
      "famous duos",
      "Greek gods",
      "fictional kings or queens",
      "jobs that need a uniform",
      "famous people named John",
      "famous people with matching initials",
      "US first ladies",
      "Founding Fathers",
      "explorers",
      "famous women in history",
      "celebrities who changed their name",
      "inventors",
      "philosophers",
      "famous ancient Greeks or Romans",
      "wars",
      "ancient civilizations",
      "pharaohs or Egyptian gods",
      "comedians",
      "authors",
      "poets",
      "scientists who aren't Einstein",
      "billionaires",
      "tech company founders",
      "famous twins",
      "royal family members, any country",
      "astronauts",
      "pirates, real or fictional",
      "civil rights leaders",
      "jobs that start with <em>P</em>",
      "jobs that didn't exist 30 years ago",
      "jobs where you work at night",
      "jobs in a hospital",
      "celebrities with a famous parent",
      "US vice presidents",
      "fashion designers",
      "famous redheads",
      "news anchors",
      "Nobel Prize winners",
      "dancers",
      "models",
      "judges, real or TV",
      "famous Davids",
      "famous Jennifers",
      "celebrities over 80",
      "TV moms",
      "TV dads",
      "inventions from before 1900",
      "things from the 1980s",
      "things from the 1990s",
      "things from the 2000s",
      "toys from your childhood",
      "jobs that need a degree",
      "historical figures called <em>the Great</em>",
      "celebrities with a famous sibling",
      "Filipino or Filipino American celebrities"
    ]
  },
  {
    id: "curve",
    name: "Curveballs",
    q: [
      "things that are yellow",
      "things that are orange",
      "things that are round",
      "things that are cold",
      "things that are sticky",
      "things that melt",
      "things that smell good",
      "things people are afraid of",
      "things that come in pairs",
      "things that have wheels",
      "things that fly that <em>aren't</em> birds",
      "things you'd see at a wedding",
      "things at a carnival",
      "things in a hospital",
      "things you do on a first date",
      "things you'd say after stubbing your toe, keep it clean",
      "things people do on Sundays",
      "nicknames for grandma",
      "dances",
      "things that are hot",
      "things that are purple",
      "things that are fluffy",
      "things that pop",
      "things that bounce",
      "things that are loud",
      "things that are heavy",
      "things with teeth that aren't animals",
      "things with a tail that aren't animals",
      "things that are sharp",
      "things that spin",
      "things bigger than a car",
      "things smaller than a coin",
      "things that are pink",
      "things that stink",
      "things you can fold",
      "things you shouldn't touch",
      "things that are free",
      "things that expire",
      "things with stripes that aren't animals",
      "things to bring to a potluck",
      "things that cost more than $1,000",
      "things you'd buy at an airport",
      "things you'd do if you won the lottery",
      "excuses for being late",
      "things people shout at concerts",
      "things you'd never say to your boss",
      "things kids are scared of",
      "things that make people cry",
      "things a magician uses",
      "superpowers",
      "things you'd save from a house fire",
      "things you can do in under a minute",
      "things with a lid",
      "things with a remote",
      "things that are slippery",
      "things that come in a box",
      "lies parents tell kids",
      "triangle-shaped things",
      "things with keys that aren't keyboards",
      "things that go up and down",
      "things that are see-through",
      "things that ring",
      "things that get wet",
      "things that are older than your grandparents"
    ]
  },
  {
    id: "adult",
    name: "After Dark",
    adult: true,
    q: [
      "cocktails",
      "words that mean <em>drunk</em>",
      "hangover cures",
      "drinking games",
      "beer brands",
      "things you shouldn't text your ex",
      "dating app red flags",
      "cheesy pickup lines",
      "things that ruin a first date",
      "things people do when they're drunk",
      "reasons people get dumped",
      "risky places to make out",
      "celebrities on your hall pass list",
      "things at a bachelorette party",
      "things that happen at a bachelor party",
      "things people lie about on dating apps",
      "things you'd never admit to your parents",
      "types of shots",
      "liquor brands",
      "types of wine",
      "excuses to leave a party early",
      "things you hide when your parents visit",
      "things you'd say to get out of a speeding ticket",
      "embarrassing places to fall asleep",
      "fake reasons to call in sick",
      "things people do in Vegas",
      "things that are better drunk",
      "things you'd find in a frat house",
      "swear words in another language",
      "slang words for butt",
      "things that get you kicked out of a bar",
      "regrets from your 20s",
      "things you shouldn't Google at work",
      "things that happen on a girls' or guys' trip",
      "signs of a walk of shame",
      "sexy Halloween costumes",
      "things in a nightstand drawer",
      "things that kill the mood",
      "jobs romance novel heroes have",
      "celebrity sex symbols",
      "celebrity scandals",
      "tattoos people regret",
      "things people do at 2 a.m.",
      "late-night drunk foods",
      "awkward things at an office party",
      "excuses for not texting back",
      "pet names couples use",
      "things couples fight about",
      "lies people tell on a first date",
      "things people do to look cool at a bar",
      "bar foods",
      "drinks with an umbrella",
      "songs that get a party going",
      "signs a date is going well",
      "signs your friend is drunk",
      "things people text at 3 a.m.",
      "breakup lines",
      "reasons to unfollow someone",
      "things you'd do if no one was watching",
      "celebrity breakups",
      "things you'd never do on a first date",
      "things you only do on vacation",
      "casino games",
      "things you'd bet money on",
      "reasons people get divorced",
      "innocent words that sound dirty",
      "foods that sound dirty",
      "things that vibrate",
      "things you lie to your doctor about",
      "excuses for a hickey",
      "things people do in a hot tub",
      "things that are better in the dark",
      "things you'd confess on your deathbed",
      "dumb reasons people get arrested",
      "excuses for being hungover at work",
      "drinking terms",
      "things at a dive bar",
      "things that happen after the open bar at a wedding",
      "things your grandma shouldn't see on your phone",
      "things people do on spring break",
      "words for getting dumped",
      "things people do at karaoke after midnight",
      "red flags in a roommate",
      "things you'd do with a fake ID",
      "famous movie make-out scenes",
      "reasons to swipe left"
    ]
  }
];
